logdir: "./experiments/admac/test_config"
state_dict: "./experiments/admac/test_config/best_loss_state_dict.pth"

test:
  datadir: "./data/TextWorldACP/test"
  batch_size: 128
  num_workers: 0
  
model:
  embedding_size: 64
  rnn_hidden_size: 64
  classifier_hidden_sizes: [64]