general:
  use_cuda: true
  game_files: ["data/SaladWorld/level_1.ulx"]
  commands_files: ["data/SaladWorld/level_1_cmd.txt"]
  vocab_file: "data/SaladWorld/vocab.txt"
  eps_annealed_args:
    upper_bound: 1.0
    lower_bound: 0.2
    duration: 75_000

training:
  traning_steps: 1_200_000
  batch_size: 10
  max_steps_per_episode: 50
  loss_fn: "smooth_l1"
  use_target_network: true
  use_double_DQN: true

  replay_buffer:
    batch_size: 32
    capacity: 500_000
    alpha: 0.6    
    beta_annealed_args:
      upper_bound: 1.0
      lower_bound: 0.4
      duration: 50_000
  
  update_after: 0
  update_per_k_game_steps: 4
  target_update_tau: 0.001
  target_update_interval: 5
  discount: 0.9
  
  optimizer:
    lr: 0.001
    clip_grad_norm: 5

model:
  embedding_size: 20
  representation_rnn: [100]
  command_scorer_net: [64, 64]

checkpoint:
  on_exist: "delete"
  experiments_path: "experiments/lvl1/"
  experiment_tag: "s120"
  experiment_description: "lvl 1, 120 steps"
  save_frequency: 10_000
